// <auto-generated />
namespace iProjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Prior : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Prior));
        
        string IMigrationMetadata.Id
        {
            get { return "201506111158566_Prior"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
